kind = "web"
previewPath = "/"
title = "Ciné Open"
version = "1.0.0"
id = "artifacts/cine-open"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20630

[services.development]
run = "pnpm --filter @workspace/cine-open run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/cine-open", "run", "build" ]
publicDir = "artifacts/cine-open/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20630"
BASE_PATH = "/"
